version: '3.6'

services:
  production_e_organico:
    build: .
    entrypoint: sh -c "yarn && yarn start"
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"