version: '3.6'

services:
  dev_e_organico:
    build: .
    container_name: dev_e_organico
    entrypoint: sh -c "yarn && yarn start:dev"
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"