export const enum keys {
  MARKETS = 'MARKETS',
  PRODUCTS = 'PRODUCTS',
  PRODUCERS = 'PRODUCERS',
  PRODUCER_PRODUCTS = 'PRODUCER_PRODUCTS',
  PAYMENTS = 'PAYMENTS',
  UNIT_MEASURES = 'UNIT_MEASURES'
}
